POST
Content-type: application/json

{
  "email": "thiagoe.ssp@gmail.com",
  "name": "Thiago"
}

###

POST http://localhost:5001
Content-type: application/json

{
  "email": "teste14@teste.com",
  "name": "Teste14"
}
